import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import pytest
from kapampangan_mt.lexicon import Lexicon
from kapampangan_mt.segmenter import MorphologicalSegmenter, SegmenterConfig


@pytest.fixture(scope="session")
def lexicon():
    """A small, FROZEN lexicon.

    Tests must not read ``data/lexicon`` — that directory is regenerated by
    ``scripts/10_ingest_dataset.py`` from whatever dictionary the project
    currently has, so assertions against it break whenever the data changes.
    """
    return Lexicon.load(ROOT / "tests" / "fixtures" / "lexicon")


@pytest.fixture(scope="session")
def segmenter(lexicon):
    return MorphologicalSegmenter(lexicon)


@pytest.fixture(scope="session")
def strict_segmenter(lexicon):
    return MorphologicalSegmenter(lexicon, config=SegmenterConfig(strict_thesis_mode=True))
