export function Step({ title, children }) {
  return <details className="process-step"><summary>{title}</summary><div className="process-body">{children}</div></details>;
}
export function Chips({ values }) {
  return <div className="process-chips">{values.map((v,i)=><code key={i}>{String(v).replaceAll(" ", "␠")}</code>)}</div>;
}
export function TranslationProcess({ result, audit }) {
  return <section className="process-section" aria-label="Translation process">
    <h2>How the translation was produced</h2>
    <p>Following the proposal’s source-to-target pipeline. Expand a stage to inspect the saved result. Neural stages explain the architecture; they are not attention visualizations.</p>
    {audit?.errors?.map(w=><p className="error-banner" key={w}>{w}</p>)}
    {!result && <p>Run a comparison to see actual input IDs and generated tokens.</p>}
    {['baseline','custom'].map(key=>{
      const r=result?.[key], p=r?.process;
      return <Step key={key} title={key==='baseline'?'Plain BPE → Filipino':'Hard-constrained Morph-BPE → Filipino'}>
        {!p ? <p>No translation trace yet.</p> : <>
          <Step title="1. Normalize input and tokenize"><p>{p.tokenization.normalized_text}</p><Chips values={p.tokenization.tokens.map(t=>t.token)}/><p>Saved vocabulary and merge rules; no runtime lexicon lookup.</p></Step>
          <Step title="2. Convert source IDs and build attention mask"><p>PAD/UNK IDs are converted to NLLB’s layout; BOS and EOS surround the sequence.</p><b>Model input IDs</b><Chips values={p.tokenization.model_source_ids}/><b>Attention mask</b><Chips values={p.attention_mask}/></Step>
          <Step title="3. Source embeddings and encoder"><p>Source table: {p.embedding_shape.join(' × ')}. This condition’s trained vectors enter NLLB’s frozen encoder, where self-attention and feed-forward layers create contextual source representations.</p></Step>
          <Step title="4. Decoder, output projection and token selection"><p>The frozen decoder attends to the source representations. Output projection scores the native target vocabulary. Autoregressive beam search uses {p.beams} beams, up to {p.max_new_tokens} new tokens, targeting {p.target_language}.</p><b>Actual generated IDs</b><Chips values={p.output_ids}/><b>Native target tokens (including controls)</b><Chips values={p.output_tokens}/></Step>
          <Step title="5. Decode Filipino output"><p>{r.translation}</p><p>Special control tokens are removed during decoding. {r.cache_hit?'This result was retrieved from the translation cache.':'This result was generated by the model.'}</p></Step>
        </>}
      </Step>;
    })}
    <Step title="Training and evaluation are separate"><p>Only source embeddings were adapted; the pretrained encoder/decoder weights stay frozen. BLEU and chrF++ require reference translations and are calculated in the evaluation notebook. A live example does not establish statistical significance.</p></Step>
  </section>;
}
export function TokenizationProcess({ result }) {
  if (!result) return null;
  return <section className="process-section"><h2>Tokenization, step by step</h2>
    <p>This tab uses the weighted penalty-32 MorphBPE artifact, Plain BPE and a separately trained Unigram-LM control. The translation checkpoint uses a different, hard-constrained Morph-BPE artifact.</p>
    <Step title="1. Prepare the same input"><p>Remove user-supplied | reference markers, normalize Unicode, and isolate words, spaces and punctuation.</p><p>{result.clean_text}</p><Chips values={result.process?.pretokens || []}/></Step>
    {['MorphBPE','Plain BPE','Unigram-LM'].map(name=><Step key={name} title={'2. Inspect '+name+' tokenization'}>
      {name==='Unigram-LM' ? <><p>Unigram uses its learned piece scores to select a segmentation. It has no BPE merge ranks; the pieces below are its actual output.</p><Chips values={result.splits[name].flat()}/>
        {(result.process?.traces[name] || []).map((t,i)=><Step key={i} title={t.surface+' — best-path calculation'}><p>At each character end position, retain the highest cumulative learned-piece score. Backtrack from the final position to obtain the output; consecutive unknown pieces are combined.</p><ol>{t.steps.map(s=><li key={s.end}>End {s.end}: best incoming piece {s.piece}, from position {s.start}, cumulative score {s.score.toFixed(4)}</li>)}</ol><Chips values={t.final_tokens}/></Step>)}
      </> : <>
        <p>{name==='MorphBPE'?'During training, allowed frequency minus 32 times crossing frequency ranks pairs; protected training joins cannot merge.':'During training, adjacent-pair frequency determines merge order without morphological protection.'} Runtime uses only the exported vocabulary and merge ranks.</p>
        {(result.process?.traces[name] || []).map((t,i)=><Step key={i} title={t.surface+' — '+(t.shortcut?'vocabulary match':t.steps.length+' merge steps')}>
          {t.shortcut ? <p>The complete surface is in the vocabulary; no merge loop runs.</p> : <><b>Initial characters</b><Chips values={t.characters}/><ol>{t.steps.map(s=><li key={s.step}>Merge {s.chosen.left} + {s.chosen.right} → {s.chosen.result} (rank {s.chosen.rank})<Chips values={s.units_after}/></li>)}</ol></>}
          <b>Final tokens</b><Chips values={t.final_tokens.map(x=>x.token)}/><b>Token IDs</b><Chips values={t.final_tokens.map(x=>x.id)}/>
        </Step>)}
      </>}
    </Step>)}
    <Step title="3. Compare the resulting pieces"><p>All conditions receive the same clean input. Fertility is pieces per whitespace-delimited input unit here; punctuation can contribute pieces. Boundary and consistency scores require supplied reference annotations. Those annotations are user input, not independently validated gold.</p><p>The proposal’s primary intrinsic comparison is MorphBPE versus Unigram-LM; Plain BPE is an additional control.</p></Step>
  </section>;
}
